import type { Metadata } from 'next';
import './globals.css';
import React, { ReactNode } from 'react';
import { Providers } from '@/app/providers';

import { Manrope } from 'next/font/google'
import Apollo from '@/app/apolloWrpapper';

const manrope = Manrope({
    weight: ['200', '300', '400', '500', '600', '700', '800'],
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface IRootLayout {
    children: ReactNode
    host: string
    cookie: string
}

export default function RootLayout({ host, children, cookie }: IRootLayout) {
    return (
        <html>
        <head>
            <title>Beregi</title>
            <meta name="viewport" content="width=device-width intial-scale=1"/>
            <link rel="icon" href="./favicon.ico"/>
        </head>
        <body className={`${manrope.className} antialiased`}>
        <Apollo cookie={cookie} host={host}>
            <Providers>{children}</Providers>
        </Apollo>
        </body>
        </html>
    );
}
