import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { Providers } from '@/app/providers';

import { Manrope } from 'next/font/google'

const manrope = Manrope({
    weight: ['200', '300', '400', '500', '600', '700', '800'],
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
        <head>
            <title>Beregi</title>
            <meta name="viewport" content="width=device-width intial-scale=1"/>
            <link rel="icon" href="./favicon.ico"/>
        </head>
        <body className={`${manrope.className} antialiased`}>
        <Providers>{children}</Providers>
        </body>
        </html>
    );
}
